### ISSUE TITLE
Special Needs Training Slides 

### ISSUE THREAD

**Issue by lilyhem** [bitprj/PrimaryEd#1]
- [x] Rough draft slides 

- [x] Peer review with Primary members 

- [x] Improve slides

- [x] add ideas such as "not all disabilities are the same","not all students learn the same way", "based on appearance alone, you cannot tell what type of disability a child has"...

- [x] Spread out the slides information 

- [x] Add resources from campus

- [x] add information for autism spectrum disorders 

- [x] replace slide backgrounds with Town hall 

- [x] Email professionals for feedback

**Comment by shreyagupta98** [comment]
Link to slides: https://docs.google.com/presentation/d/1anil175pyUJrkmUHfDBWuXrTh5BoAWzUJouG7FJ-Za0/edit#slide=id.g7232cfd26e_0_3

**Comment by lilyhem** [comment]
Link to slides: https://docs.google.com/presentation/d/1P89ugQSuqEByTWymtp-ESEUXXVIQD81jBWz67Uf3a14

**Comment by lilyhem** [comment]
- [ ] change slides and general tips according to feedback 

- [ ] film for webinar
